[package]
name = "universe-players"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "1.0.0"
http-client = "6.5.3"
http-types = "2.12.0"
curl = "0.4.39"
serde_json = "1.0"
